export const state = () => ({
  // widget products
  grailWidgets: [
    {
      id: 'grail-widget-00',
      type: 'Standards',
      title: 'ISO 27001/ISO 27002',
      snippet: [
        'Consultancy.',
        'Definition of objectives.',
        'Creation of a Master Plan.',
        'ISMS implementation.',
      ],
      image: 'gr-01-iso.svg',
      icon: 'g-01-iso.svg',
      colors: ['#F3477C', '#EC4552'],
    },
    {
      id: 'grail-widget-01',
      type: 'Standards',
      title: 'GDPR',
      snippet: ['Consultancy.', 'Current situation.', 'Action plan.'],
      image: 'gr-02-gdpr.svg',
      icon: 'g-02-gdpr.svg',
      colors: ['#F3477C', '#EC4552'],
    },
    {
      id: 'grail-widget-02',
      type: 'Standards',
      title: 'National Security Scheme (ENS)',
      snippet: ['Creation of a Master Plan.', 'Implantation.', 'Maintenance.'],
      image: 'gr-03-ens.svg',
      icon: 'g-03-ens.svg',
      colors: ['#F3477C', '#EC4552'],
    },
    {
      id: 'grail-widget-03',
      type: 'Solutions',
      title: 'Implementation of Solutions',
      snippet: [
        'Analysis, design and implementation of cyberSecurity solutions.',
        'Implementation and integration of IT infrastructures.',
        'Bastion of devices.',
      ],
      image: 'gr-04-solutions.svg',
      icon: 'g-04-solutions.svg',
      colors: ['#FDC037', '#EF9D1E'],
    },
    {
      id: 'grail-widget-04',
      type: 'Solutions',
      title: 'Managed Security',
      snippet: [
        'Monitoring and correlation of events.',
        'Vulnerability management.',
        'Operation and administration of the security infrastructure.',
        'Incident response.',
      ],
      image: 'gr-05-managed.svg',
      icon: 'g-05-managed.svg',
      colors: ['#FDC037', '#EF9D1E'],
    },
    {
      id: 'grail-widget-05',
      type: 'Solutions',
      title: 'Industrial Security',
      snippet: [
        'Control of processes, people and technologies for the protection of industrial infrastructures.',
        'Industrial Control Systems (ICS) Security.',
        'SCADA Security.',
        'Monitoring of industrial systems.',
      ],
      image: 'gr-06-industry.svg',
      icon: 'g-06-industry.svg',
      colors: ['#FDC037', '#EF9D1E'],
    },
    {
      id: 'grail-widget-06',
      type: 'Audits',
      title: 'Analysis and Forensic Expertise',
      snippet: [
        'Computer expert opinions for defense in the criminal field.',
        'Device analysis and verification of actions carried out.',
        'Software Analysis.',
        'Network Analysis.',
      ],
      image: 'gr-07-forensic.svg',
      icon: 'g-07-forensic.svg',
      colors: ['#64D6BE', '#20AE8F'],
    },
    {
      id: 'grail-widget-07',
      type: 'Audits',
      title: 'Software Audits',
      snippet: [
        'Detection of code vulnerabilities.',
        'Analysis of communication protocols.',
        'Implementation of secure development methodology.',
        'Analysis of applications for mobile devices.',
      ],
      image: 'gr-08-software.svg',
      icon: 'g-08-software.svg',
      colors: ['#64D6BE', '#20AE8F'],
    },
    {
      id: 'grail-widget-08',
      type: 'Formation',
      title: 'Training',
      snippet: [
        'Training for non-technical personnel.',
        'Awareness plans.',
        'Conferences and talks.',
        'Specific courses for personnel I.',
      ],
      image: 'gr-09-training.svg',
      icon: 'g-09-training.svg',
      colors: ['#28C0F7', '#5C81FE'],
    },
  ],
})
